name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Test run
      uses: ./
      with:
        directory: .test
        snakefile: .test/Snakefile
        args: "--cores 1"

    - name: Test containerize
      uses: ./
      with:
        directory: .test
        snakefile: .test/Snakefile
        args: "--cores 1"
        task: "containerize"
  
    - name: Show Dockerfile
      run: |
        cat Dockerfile
