name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test run
        uses: ./
        with:
          directory: .test
          snakefile: .test/Snakefile
          args: "--cores 1"

      - name: Test containerize
        uses: ./
        with:
          directory: .test
          snakefile: .test/Snakefile
          install-apptainer: true
          args: "--cores 1"
          task: "containerize"

      - name: Show Dockerfile
        run: |
          cat Dockerfile
